name: build and deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: fetch soure code
        uses: actions/checkout@v2

      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: 12.18.3

      - name: node cache
        uses: actions/cache@v2
        env:
          cache-name: modules-node
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: dependencies
        run: yarn install --frozen-lockfile

      - name: build
        run: yarn build && yarn export
        env:
          NODE_ENV: dev

      - name: deploy
        uses: docker://amazon/aws-cli:2.1.18
        with:
          args: s3 sync out s3://facet.ninja/ --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-west-2"